export const SEARCH_PHOTOS = 'SEARCH_PHOTOS'
export const UPDATE_QUERY = 'UPDATE_QUERY'
export const RETRIEVE_MORE_PHOTOS = 'RETRIEVE_MORE_PHOTOS'
export const REMOVE_PREVIOUS_QUERY = 'REMOVE_PREVIOUS_QUERY'

export const UPDATE_COLUMNS = 'UPDATE_COLUMNS'

